OUTPUT_DIR: '/scratch/users/edwinpan/results'
EXP_NAME: 'b5_ne3_ExpandNetLoss'
CHECKPOINT_SAVE_PATH: 'checkpoints'
SUMMARY_INTERVAL: 1
PRINT_INTERVAL: 2
TEST_PRINT_INTERVAL: 3

# Loss parameters
LOSS:
  SEP_LOSS: True
  LAMBDA: 0.5

# Training parameters
TRAIN:
  LOSS_FUNC: 'ExpandNetLoss' # ['ExpandNetLoss', 'HaarLoss', 'LPIPSLoss', 'LPIPSLoss_L2', 'SSIMLoss']
  BATCH_SIZE: 3
  VAL_BATCH_SIZE: 5
  NUM_EXPOSURES: 3
  NUM_META_TR_ITER: 200 # 
  NUM_TASK_TR_ITER: 3 # Number of task-specific inner loops
  META_LR: 0.005
  TASK_LR: 0.01
  
# Evaluation parameters
EVAL:
  LOSS_FUNC: 'ExpandNetLoss' # ['ExpandNetLoss', 'HaarLoss', 'LPIPSLoss', 'LPIPSLoss_L2', 'SSIMLoss']
  BATCH_SIZE: 10
  NUM_EXPOSURES: 3
  NUM_TASK_TR_ITER: 3
  TASK_LR: 0.1

# Utility parameters
UTILS:
  GAMMA: 2.2