OUTPUT_DIR: 'results'
EXP_NAME: 'default'
CHECKPOINT_SAVE_PATH: 'checkpoints'
SUMMARY_INTERVAL: 1
PRINT_INTERVAL: 3
TEST_PRINT_INTERVAL: 5

# Loss parameters
LOSS:
  SEP_LOSS: True
  LAMBDA: 0.5

# Training parameters
TRAIN:
  BATCH_SIZE: 3
  NUM_EXPOSURES: 5
  NUM_META_TR_ITER: 200 # 
  NUM_TASK_TR_ITER: 1 # Number of task-specific inner loops
  META_LR: 0.001
  TASK_LR: 0.4
  
# Utility parameters
UTILS:
  GAMMA: 2.2