OUTPUT_DIR: '/scratch/users/edwinpan/results'
EXP_NAME: 'b2_ne3_lr0p01_Debevec_LPIPS'
CHECKPOINT_SAVE_PATH: 'checkpoints'
SUMMARY_INTERVAL: 1
PRINT_INTERVAL: 2
TEST_PRINT_INTERVAL: 3

# Training parameters
TRAIN:
  LOSS_FUNC: 'LPIPSLoss' # ['ExpandNetLoss', 'HaarLoss', 'LPIPSLoss', 'LPIPSLoss_L2', 'SSIMLoss']
  MODEL: 'Unet' # [Unet, Resnet]
  INCLUDE_UNET_OUTPUTS: False
  BATCH_SIZE: 2
  VAL_BATCH_SIZE: 3
  NUM_EXPOSURES: 3
  NUM_META_TR_ITER: 200 # 
  NUM_TASK_TR_ITER: 3 # Number of task-specific inner loops
  META_LR: 0.005
  TASK_LR: 0.01
  
# Evaluation parameters
EVAL:
  LOSS_FUNC: 'LPIPSLoss_L2' # ['ExpandNetLoss', 'HaarLoss', 'LPIPSLoss', 'LPIPSLoss_L2', 'SSIMLoss']
  NUM_TASK_TR_ITER: 3 # Always keep at 3 for evaluation (since we only want to evaluate on 'real' images)
  NUM_EXPOSURES: 3
  TASK_LR: 0.1

# Utility parameters
UTILS:
  GAMMA: 2.2